apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-events

# https://argoproj.github.io/argo-events/quick_start/
# https://argoproj.github.io/argo-events/installation/
# https://github.com/argoproj/argo-events
resources:
  - github.com/argoproj/argo-events/manifests/cluster-install
  - github-event.yaml
  - ingress.yaml
  - https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/sensors/github.yaml
